<template>
  <div>
  </div>
</template>

<script>
export default {
  methods:{
    play(id){
      player.loadVideoById(id)
      player.playVideo()
    },
    pause(){
      player.pauseVideo()
    },
    myVolume(){
        player.setVolume()
    },
    nextSong(){
      player.nextVideo()
    },
    previousSong(){
      player.previousVideo()
    },
    loadPlaylist(){
      player.loadPlaylist()
    }
  }
}
</script>